name: "Checks URL action"
description: "Checks page status from url"
author: 'Benoit Serrano'
branding:
  icon: 'activity'  
  color: 'green'
inputs:
  url:
    description: 'The URL to check'
    required: true
  minExpectedRegex:
    description: 'The minimum regex that the URI must match to obtain a good grade'
    required: false 
  exactExpectedRegex:
    description: 'The regex that the URI must match to obtain the maximum grade'
    required: false
  output:
    description: 'Filename for stats reports'
    default: 'url_status.json'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
      
